# Generated by Django 5.0.3 on 2025-08-25 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_training_schedule_question_type_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='training_schedule_temp',
            name='deleted',
        ),
    ]
