# Generated by Django 5.0.3 on 2025-09-17 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_training_schedule_temp_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder_master',
            name='syllabus',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='login',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='login',
            name='otp_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='login',
            name='otp_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='training_schedule_temp',
            name='deleted',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='test_master',
            name='test_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
