# Generated by Django 5.0.3 on 2025-12-15 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_dev_remarks_question_paper_master_audio_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='languages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tamil_word', models.CharField(max_length=255)),
                ('english_word', models.CharField(max_length=255)),
                ('hindi_word', models.CharField(blank=True, max_length=255, null=True)),
                ('malayalam_word', models.CharField(blank=True, max_length=255, null=True)),
                ('telugu_word', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
