# Generated by Django 5.0.3 on 2025-08-25 05:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='training_schedule',
            name='question_type_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.question_type'),
        ),
        migrations.AddField(
            model_name='training_schedule',
            name='skill_type_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.skill_type'),
        ),
        migrations.AddField(
            model_name='training_schedule_temp',
            name='batch_skill',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='training_schedule_temp',
            name='question_type',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='training_schedule_temp',
            name='skill_type',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.CreateModel(
            name='folder_master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('deleted', models.IntegerField(default=0)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('dtm_created', models.DateTimeField(blank=True, null=True)),
                ('folder_logo', models.BinaryField(blank=True, null=True)),
                ('skill_type_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.skill_type')),
            ],
        ),
    ]
