# Generated by Django 5.0.3 on 2025-09-17 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_folder_master_syllabus_login_mobile_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test_master',
            name='test_name',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
