# Generated by Django 5.0.3 on 2025-11-06 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question_paper_master',
            old_name='dev_remarks',
            new_name='audio_text',
        ),
    ]
