# Generated by Django 5.0.3 on 2025-12-15 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_languages'),
    ]

    operations = [
        migrations.AddField(
            model_name='languages',
            name='created_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='languages',
            name='deleted',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='languages',
            name='dtm_created',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='languages',
            name='modified_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
