# Generated by Django 5.0.3 on 2025-12-15 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_languages_created_by_languages_deleted_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='languages',
            index=models.Index(fields=['tamil_word'], name='idx_lang_tamil'),
        ),
        migrations.AddIndex(
            model_name='languages',
            index=models.Index(fields=['english_word'], name='idx_lang_english'),
        ),
        migrations.AddIndex(
            model_name='languages',
            index=models.Index(fields=['hindi_word'], name='idx_lang_hindi'),
        ),
        migrations.AddIndex(
            model_name='languages',
            index=models.Index(fields=['malayalam_word'], name='idx_lang_malayalam'),
        ),
        migrations.AddIndex(
            model_name='languages',
            index=models.Index(fields=['telugu_word'], name='idx_lang_telugu'),
        ),
        migrations.AddIndex(
            model_name='languages',
            index=models.Index(fields=['deleted'], name='idx_lang_deleted'),
        ),
        migrations.AddIndex(
            model_name='languages',
            index=models.Index(fields=['tamil_word', 'english_word'], name='idx_lang_ta_en'),
        ),
        migrations.AlterModelTable(
            name='languages',
            table='languages',
        ),
    ]
