# Generated by Django 5.0.3 on 2025-12-15 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_languages_idx_lang_tamil_languages_idx_lang_english_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='languages',
        ),
    ]
