# Generated by Django 5.0.3 on 2025-12-24 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_delete_languages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question_paper_master',
            name='dtm_modified',
        ),
        migrations.AddField(
            model_name='question_paper_master',
            name='communication_category',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
